import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

# --- DYNAMIC PATHING SETUP ---
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)

# Pointing to the files generated by your training script
test_file = os.path.join(project_root, 'Dataset', 'Step_1_test_data.csv')
model_path = os.path.join(project_root, 'Models', 'step_1_physics_model.keras')
plots_dir = os.path.join(project_root, 'Output_plots')

print("===========================================")
print("📡 INITIALIZING PHYSICS INFERENCE PIPELINE")
print("===========================================\n")

# --- 1. LOAD THE DATA AND MODEL ---
print(f"📂 Loading noisy physics test data: {test_file}")
try:
    test_df = pd.read_csv(test_file)
except FileNotFoundError:
    print(f"❌ Error: Could not find '{test_file}'.")
    exit()

print(f"🧠 Loading trained Physics AI: {model_path}")
try:
    model = load_model(model_path)
except Exception as e:
    print(f"❌ Error loading model: {e}")
    exit()

# --- 2. PREPARE INPUTS ---
# The AI must look at the X, Y, AND the noisy RSRP signal
X_test = test_df[['X_Location', 'Y_Location', 'RSRP_dBm']].values
y_actual = test_df['Target_Beam'].values

# --- 3. RUN PREDICTIONS ---
print("\n🚀 Asking AI to predict Beam IDs in a noisy environment...")
raw_predictions = model.predict(X_test)
y_pred = np.argmax(raw_predictions, axis=1)

# --- 4. FIND THE ERRORS ---
# Let's track exactly which users the AI got wrong
accuracy = np.mean(y_pred == y_actual)
errors = y_pred != y_actual 
print(f"🎯 Inference Accuracy: {accuracy * 100:.2f}%")

# --- 5. VISUAL PROOF ---
print("\n📊 Generating Side-by-Side Physics Comparison Plot...")
os.makedirs(plots_dir, exist_ok=True)
plt.figure(figsize=(14, 6))

# Subplot 1: Ground Truth (What the beams SHOULD be)
plt.subplot(1, 2, 1)
plt.scatter(test_df['X_Location'], test_df['Y_Location'], c=y_actual, cmap='hsv', alpha=0.6)
plt.plot(0, 0, marker='^', color='black', markersize=15, label='5G Tower')
plt.title("Actual Target Beams (Ground Truth)")
plt.xlabel("X Coordinate (Meters)")
plt.ylabel("Y Coordinate (Meters)")
plt.grid(True, linestyle='--', alpha=0.5)

# Subplot 2: AI Predictions WITH Errors Highlighted!
plt.subplot(1, 2, 2)
# Plot all predictions lightly
plt.scatter(test_df['X_Location'], test_df['Y_Location'], c=y_pred, cmap='hsv', alpha=0.3)
# Overplot the errors in solid Black so they stand out
plt.scatter(test_df['X_Location'][errors], test_df['Y_Location'][errors], color='black', marker='x', label='AI Errors', alpha=0.8)

plt.plot(0, 0, marker='^', color='red', markersize=15, label='5G Tower')
plt.title(f"AI Predictions (Errors Marked as 'X')")
plt.xlabel("X Coordinate (Meters)")
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend()

plot_path = os.path.join(plots_dir, 'step_1_physics_comparison.png')
plt.savefig(plot_path, dpi=300, bbox_inches='tight')
print(f"✅ Visual comparison saved to: {plot_path}")
plt.show()